# Test goal: Integration testing for gmxapi support and client Python package.
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   GPU: unspecified
#   GROMACS: according to merge request target branch
#   GROMACS MPI: thread-MPI
#   gmxapi: library as bundled with GROMACS
#   Scope: build, install, test
# Test implementation choices (free to change as needed):
#   GROMACS branch: repository version
#   gmxapi Python package: sources from python_packaging/
#   compiler: clang-14
#   Features: regular precision FP

.gmxapi:clang-14:
  extends:
    - .use-clang:base
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-22.04-llvm-14-cuda-12.1.0
  stage: test
  variables:
    CMAKE: /usr/local/cmake-3.30.3/bin/cmake
    COMPILER_MAJOR_VERSION: 14
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    PY_UNIT_TEST_XML: $CI_PROJECT_DIR/py-JUnitTestResults.xml
    PY_MPI_UNIT_TEST_XML: $CI_PROJECT_DIR/py-mpi-JUnitTestResults.xml
  script:
    - source $INSTALL_DIR/bin/GMXRC
    - source $VENVPATH/bin/activate
    - GROMACS_ROOT=$PWD/$INSTALL_DIR OMP_NUM_THREADS=1 bash -x admin/ci-scripts/build-and-test-py-gmxapi.sh
  artifacts:
    reports:
      junit:
        - $PY_UNIT_TEST_XML
        - $PY_MPI_UNIT_TEST_XML
    when: always
    expire_in: 1 week
  needs:
    - job: gromacs:clang-14:build
      artifacts: true

gmxapi:clang-14:py-3.10:
  extends:
    - .gmxapi:clang-14
  rules:
    - !reference [.rules:merge-requests, rules]
  variables:
    VENVPATH: "/root/venv/py3.10"
