# Build and test GROMACS client code to monitor implementation of specified APIs.
#
# Job configurations are inside api-client.matrix/ directory.

.sample_taf:
  stage: test
  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 1Gi
    KUBERNETES_MEMORY_REQUEST: 1Gi
  script:
    - export GROMACS_DIR=$PWD/$INSTALL_DIR
    - export GMX_SUFFIX
    - export CMAKE
    - export GMX_DOUBLE
    - bash -x admin/ci-scripts/build-taf-template.sh

# Consumers must set job.variables.COMPILER_MAJOR_VERSION!
.sample_restraint:clang:
  extends:
    - .use-clang:base
  stage: test
  variables:
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    PLUGIN_TEST_XML: $CI_PROJECT_DIR/py-JUnitTestResults.xml
    PLUGIN_MPI_TEST_XML: $CI_PROJECT_DIR/py-mpi-JUnitTestResults.xml
  script:
    - source $INSTALL_DIR/bin/GMXRC
    - source $VENVPATH/bin/activate
    - export GMX_SUFFIX
    - export KUBERNETES_CPU_REQUEST
    - export CC=clang-${COMPILER_MAJOR_VERSION}
    - export CXX=clang++-${COMPILER_MAJOR_VERSION}
    - |
      GROMACS_ROOT=$PWD/$INSTALL_DIR \
      OMP_NUM_THREADS=1 \
      bash -x admin/ci-scripts/build-and-test-sample_restraint.sh
  artifacts:
    reports:
      junit:
        - $PLUGIN_TEST_XML
        - $PLUGIN_MPI_TEST_XML
    paths:
      - $BUILD_DIR/python_packaging/sample_restraint/build/CMakeFiles/*.log
    when: always
    expire_in: 1 week

include:
  - local: '/admin/gitlab-ci/api-client.matrix/gromacs-main.gitlab-ci.yml'
  - local: '/admin/gitlab-ci/api-client.matrix/gromacs-main-mpi.gitlab-ci.yml'
