# Test goal: Initial build with close-to-default settings that always needs to pass before follow-up CI stages run
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang
#   Build type: Debug
#   CMake: oldest supported
#   GPU: no
#   SIMD: no
#   Scope: configure, build, unit tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 24.04
#   Compiler: Clang 19
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2

simple-build:
  # Test scope: configure, build, unit tests
  extends:
    - .use-ccache
    - .use-clang:base
  stage: pre-build
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-llvm-19

  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    KUBERNETES_CPU_LIMIT: 8
    KUBERNETES_CPU_REQUEST: 4
    KUBERNETES_MEMORY_REQUEST: 8Gi
    CTEST_RUN_MODE: "ExperimentalTest"
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=None"
    CMAKE_MPI_OPTIONS: "-DGMX_THREAD_MPI=ON"
    CMAKE_PRECISION_OPTIONS: "-DGMX_DOUBLE=OFF"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug"
    CMAKE_GPU_OPTIONS: "-DGMX_GPU=OFF"
    CMAKE_GMXAPI_OPTIONS: "-DGMX_PYTHON_PACKAGE=OFF"
    COMPILER_MAJOR_VERSION: 19
    BUILD_DIR: simple-build
  script:
    - bash -x admin/ci-scripts/gromacs-base-configure.sh
    - bash -x admin/ci-scripts/gromacs-base-build.sh
    - bash -x admin/ci-scripts/gromacs-base-test.sh
  artifacts:
    reports:
      junit: $BUILD_DIR/JUnitTestResults.xml
    paths:
      - $BUILD_DIR/*log
      - $BUILD_DIR/CMakeFiles/*log
    when: always
    expire_in: 1 week
